backend:
  name: git-gateway
  branch: master

media_folder: "soche-east-youth/uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "soche-east-youth/content/homepage.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Message", name: "message", widget: "text" }
